create table if not exists posts (
  id text primary key,
  title text not null,
  category text not null,
  target_sns text[] not null default '{}',
  target_audience text not null default '',
  purpose text not null default '',
  source_memo text not null default '',
  generated_text_x text not null default '',
  generated_text_instagram text not null default '',
  generated_text_facebook text not null default '',
  generated_text_threads text not null default '',
  final_text text not null default '',
  media_note text not null default '',
  scheduled_date date,
  posted_date date,
  post_url text not null default '',
  status text not null default 'ネタ',
  priority integer not null default 3,
  likes integer not null default 0,
  reposts integer not null default 0,
  comments integer not null default 0,
  impressions integer not null default 0,
  inquiries_count integer not null default 0,
  bookings_count integer not null default 0,
  ai_check_result text not null default '',
  ai_analysis text not null default '',
  improvement_memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
