import type { AgreementContent } from "@/domain/schema";

export const initialContent: AgreementContent = {
  managerProjectId: "MGR-2026-001",
  projectName: "新商品プロモーション映像",
  category: "映像制作",
  clientName: "株式会社サンプル",
  clientEmail: "contact@example.jp",
  creatorName: "東海制作",
  creatorEmail: "creator@example.jp",
  commissionedAt: "2026-06-25",
  workDescription: "新商品の魅力を伝えるWeb・SNS向けプロモーション映像の企画、撮影、編集。",
  deliverables: "60秒動画 1本／15秒縦型動画 2本",
  deliveryFormat: "MP4（H.264）",
  deliveryMethod: "クラウドストレージの共有URL",
  inScope: "企画、構成、撮影1日、編集、色調整、BGM選定",
  outOfScope: "出演者手配、遠方交通費、商品CG制作",
  fee: "350000",
  taxTreatment: "税別",
  deliveryDate: "2026-07-31",
  deliveryPlace: "オンライン納品",
  paymentDue: "2026-08-31",
  paymentMethod: "指定口座への銀行振込",
  inspectionDays: "5",
  revisionCount: "",
  additionalRevisionFee: "",
  reEditingFee: "",
  copyright: "",
  usageScope: "自社Webサイト、公式SNS、店頭サイネージ",
  portfolioPermission: "",
  portfolioTiming: "納品後すぐ",
  creditRequired: "クレジット不要",
  cancellation: "",
  dataRetention: "納品後90日",
  accidentReport: true,
  delayNotice: true,
  weatherPostponementState: "on",
  weatherPostponement: "悪天候で撮影が難しい場合は双方で順延日を相談し、追加実費は事前確認します。",
  locationPermitState: "on",
  locationPermit: "撮影場所の許可取得は発注者が行い、申請費用は発注者が負担します。",
  portraitRightsState: "on",
  portraitRights: "出演者の撮影・利用許諾は発注者が取得します。",
  musicRightsState: "on",
  musicRights: "有料BGM・素材の利用料は見積確認後、発注者が負担します。",
  liabilityLimit: "",
};
