import type { PromoData } from '../utils/promoTypes'

const creatorProjectManager: PromoData = {
  slug: 'creator-project-manager',
  title: 'クリエイター案件マネージャー',
  subtitle: '聞き漏れを、減らす。',
  url: 'creator-project-manager.vercel.app',
  status: 'β版公開中',
  theme: 'standard',
  scenes: [
    { id: 'scene-1', kind: 'hero' },
    { id: 'scene-2', kind: 'problem' },
    { id: 'scene-3', kind: 'category' },
    { id: 'scene-4', kind: 'feature' },
    { id: 'scene-5', kind: 'flow' },
    { id: 'scene-6', kind: 'ending' },
  ],
  hero: {
    title: '聞き漏れを、減らす。',
    product: 'クリエイター案件マネージャー',
    status: 'β版公開中',
  },
  problem: {
    title: '全部、聞けていますか？',
    items: [
      { label: '納品形式', checked: true },
      { label: '使用範囲', checked: true },
      { label: '修正回数', checked: true },
      { label: 'SNS掲載' },
      { label: 'クレジット表記', checked: true },
      { label: '交通費' },
      { label: '駐車場代' },
      { label: '著作権', checked: true },
      { label: '納品日', checked: true },
      { label: '支払い条件' },
      { label: '源泉徴収' },
      { label: 'キャンセル条件' },
    ],
    message: '聞いていないことは、あとから問題になることがあります。',
  },
  category: {
    title: 'クリエイターごとに、聞くべきことは違う。',
    categories: [
      { label: '映像制作', note: '撮影から納品まで', icon: 'video' },
      { label: 'カメラマン', note: '撮影条件を整理', icon: 'camera' },
      { label: 'デザイナー', note: '形式と修正を確認', icon: 'layout' },
      { label: 'イラストレーター', note: '使用範囲を明確に', icon: 'pen' },
      { label: 'ヘアメイク', note: '人数と拘束を確認', icon: 'spark' },
      { label: 'ライター', note: '文字量と校正', icon: 'file' },
      { label: '動画編集', note: '素材と尺を確認', icon: 'monitor' },
      { label: '音響', note: '収録と整音', icon: 'mic' },
      { label: 'イベント', note: '場所と進行', icon: 'briefcase' },
      { label: 'Web制作', note: '公開範囲を整理', icon: 'layers' },
      { label: 'SNS運用', note: '投稿条件を確認', icon: 'copy' },
      { label: '配信', note: '回線と機材', icon: 'wand' },
      { label: 'ナレーター', note: '尺と使用媒体', icon: 'mic' },
      { label: '3DCG', note: '形式と修正', icon: 'image' },
      { label: 'その他', note: '案件ごとに調整', icon: 'clipboard' },
    ],
  },
  feature: {
    title: '職種を選ぶだけで、聞くべきことが変わる。',
    subtitle: '同じ入力画面ではなく、仕事に合わせたヒアリングへ。',
    workspaceTitle: 'クリエイター案件マネージャー',
    workspaceStatus: 'ローカル保存済み',
    tabs: ['職業', '聞取', '見積', '確認', '納品', '請求'],
    savedLabel: '保存済み',
    documentEyebrow: 'TOKAI PRODUCTION DOCUMENT',
    documentTitle: '聞き取りシート',
    roles: [
      {
        id: 'video',
        label: '映像制作',
        note: '撮影条件と納品条件を先に整理',
        fields: [
          { id: 'shoot-date', label: '撮影日', kind: 'date', value: '2026年9月10日', width: 'half' },
          { id: 'location', label: '撮影場所', kind: 'text', value: '岐阜市内スタジオ', width: 'half' },
          { id: 'cast', label: '出演人数', kind: 'select', value: '3名', options: ['1名', '2名', '3名', '4名以上'], width: 'half' },
          { id: 'format', label: '納品形式', kind: 'select', value: '4K / MP4', options: ['Full HD', '4K / MP4', 'ProRes'], width: 'half' },
          { id: 'media', label: '使用媒体', kind: 'text', value: 'Webサイト / SNS広告', width: 'full' },
          { id: 'credit', label: 'クレジット表記', kind: 'checkbox', value: '掲載可', checked: true, width: 'half' },
        ],
      },
      {
        id: 'photo',
        label: 'カメラマン',
        note: '撮影量と仕上げ範囲を確認',
        fields: [
          { id: 'hours', label: '撮影時間', kind: 'select', value: '4時間', options: ['2時間', '4時間', '8時間'], width: 'half' },
          { id: 'shots', label: '撮影枚数', kind: 'text', value: '120枚前後', width: 'half' },
          { id: 'retouch', label: 'レタッチ', kind: 'select', value: '20枚', options: ['なし', '10枚', '20枚'], width: 'half' },
          { id: 'delivery', label: '納品写真', kind: 'select', value: 'Web共有', options: ['Web共有', 'USB', 'クラウド'], width: 'half' },
          { id: 'parking', label: '駐車場代', kind: 'checkbox', value: '別途精算', checked: true, width: 'half' },
          { id: 'sns', label: 'SNS掲載', kind: 'checkbox', value: '確認する', checked: false, width: 'half' },
        ],
      },
      {
        id: 'hairmake',
        label: 'ヘアメイク',
        note: '人数と現場環境を確認',
        fields: [
          { id: 'people', label: '対象人数', kind: 'select', value: '5名', options: ['1名', '3名', '5名', '10名以上'], width: 'half' },
          { id: 'hold', label: '拘束時間', kind: 'select', value: '6時間', options: ['3時間', '6時間', '終日'], width: 'half' },
          { id: 'room', label: '控室', kind: 'checkbox', value: 'あり', checked: true, width: 'half' },
          { id: 'rehearsal', label: 'リハーサル', kind: 'checkbox', value: '前日確認', checked: true, width: 'half' },
          { id: 'kit', label: '持込道具', kind: 'text', value: '基本キット持参', width: 'full' },
        ],
      },
      {
        id: 'design',
        label: 'デザイナー',
        note: '成果物と修正範囲を明確に',
        fields: [
          { id: 'size', label: 'サイズ', kind: 'select', value: 'A4 / SNS横長', options: ['A4', 'SNS横長', 'Webバナー'], width: 'half' },
          { id: 'format', label: '納品形式', kind: 'select', value: 'PDF / PNG', options: ['PDF', 'PNG', 'PDF / PNG'], width: 'half' },
          { id: 'revision', label: '修正回数', kind: 'select', value: '2回まで', options: ['1回', '2回まで', '別途相談'], width: 'half' },
          { id: 'source', label: '元データ', kind: 'checkbox', value: '納品なし', checked: false, width: 'half' },
          { id: 'rights', label: '使用範囲', kind: 'text', value: '自社Web / SNS', width: 'full' },
        ],
      },
    ],
  },
  flow: {
    title: '聞き取りから、仕事の流れをつくる。',
    steps: [
      { label: '聞き取り', note: '最初に確認' },
      { label: '案件情報', note: '内容を整理' },
      { label: '見積', note: '条件を反映' },
      { label: '確認', note: '認識を合わせる' },
      { label: '納品', note: '成果物を管理' },
      { label: '請求', note: 'お金を残す' },
      { label: '保存・複製', note: '次に活かす' },
    ],
  },
  ending: {
    title: '聞き取りから、仕事をもっとスムーズに。',
    product: 'クリエイター案件マネージャー',
    url: 'creator-project-manager.vercel.app',
    status: 'β版公開中',
  },
}

export default creatorProjectManager
